# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gmCmdPro.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gmCmdPro.proto',
  package='com.firevale.server2server.protocol',
  serialized_pb=_b('\n\x0egmCmdPro.proto\x12#com.firevale.server2server.protocol\"\x19\n\x0bGmOnlineNtf\x12\n\n\x02id\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GMONLINENTF = _descriptor.Descriptor(
  name='GmOnlineNtf',
  full_name='com.firevale.server2server.protocol.GmOnlineNtf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.firevale.server2server.protocol.GmOnlineNtf.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['GmOnlineNtf'] = _GMONLINENTF

GmOnlineNtf = _reflection.GeneratedProtocolMessageType('GmOnlineNtf', (_message.Message,), dict(
  DESCRIPTOR = _GMONLINENTF,
  __module__ = 'gmCmdPro_pb2'
  # @@protoc_insertion_point(class_scope:com.firevale.server2server.protocol.GmOnlineNtf)
  ))
_sym_db.RegisterMessage(GmOnlineNtf)


# @@protoc_insertion_point(module_scope)
